### PR TITLE
Ember 1.13.x (Glimmer) support

### PR DESCRIPTION
**Pull request by neojp**
Move $.inputMask code into the afterRender queue

### CODE REVIEW

**Comment by pzuraq** [comment]
@neojp Looks good, can you rebase this and the other PR you made and I'll merge them both?

**Comment by neojp** [comment]
@pzuraq Hi, it took me a while to figure it out but I think I rebased them correctly. Would you mind checking it out? Thanks for the plugin, it's proven to be very useful.

**Comment by pzuraq** [comment]
@neojp I don't think you rebased correctly, sorry about that... What you'll want to do is pull the latest from master onto your master branch.

```
git pull origin master
```

You'll need to add the repo as origin, and make sure the working branch is master (`git checkout master`)

Then you'll want to switch to your branch and do `git rebase master`. That'll replay your work on top of master. It should allow me to merge it automatically then.

**Comment by neojp** [comment]
Oh, that's too bad. I will take a look at it later tonight.

**Comment by pzuraq** [comment]
no worries. Also meant to say `upstream` not `origin` up there.

**Comment by al3x-edge** [comment]
@pzuraq @neojp Any movement for this?

**Comment by neojp** [comment]
I completely forgot about this.

**Comment by al3x-edge** [comment]
@neojp Thanks! Appreciate it =] Just finally getting past a couple other hurdles for 1.13 for us and then noticed inputmask was throwing an error in it.

**Comment by neojp** [comment]
Finally got around patching this up and it's ready to be automatically merged into master.
This should stop Glimmer from throwing errors all over the place when initializing these components.

---

There seems to be performance problems on these 2 components under Ember 1.13.0 and I will look into them as a separate issue.

1. `{{credit-card-input}}`
2. `{{phone-number-input}}`

**Comment by pzuraq** [comment]
Thanks again @neojp!

**Pull request merged**
