### PR TITLE
Add more options to number input

### PR DESCRIPTION
**Pull request by jasonbekolay**
There were some additional options from inputmask that I wanted to use, so I've implemented them.

Thanks for your work on this addon!

### CODE REVIEW

**Comment by leizhao4** [comment]
@jasonbekolay Thanks a lot for the contribution!

I will be traveling during the next 6-7 days but I will try my best to review this PR as soon as possible.

In the meantime, would you please fix the failed tests? Looks like there are some issues in `number-input`.

Thanks again!

**Comment by jasonbekolay** [comment]
For sure, I will look at fixing the tests early next week. Thanks!

**Comment by jasonbekolay** [comment]
I've modified the tests and they now pass. I typically run my tests in the browser, and it seems the unmasking doesn't quite work the same in a few cases between the browser and PhantomJS. I left my origin assertions as comments. I can remove those if you want, but if you switch from Phantom to headless Chrome for running tests, it may be worth uncommenting them.

Anyway, have a look when you have the time (no rush) and let me know if there are further changes required. Thanks!

**Comment by leizhao4** [comment]
@jasonbekolay Everything looks great! I'm going to merge it and release a new version.

And yes, Phantom does have some weird testing issues and I agree that headless Chrome is a good move. I personally haven't tried it yet though (with Travis CI). I'm guessing we need to fix some tests that were written in a wrong way to just make Phantom happy. I will try to figure it out later, but if you can help with another PR, that would be awesome too.

Thanks again!

**Comment by jasonbekolay** [comment]
Thanks for reviewing and merging!

There are a couple other tests that fail in the browser so I would assume they also fail in headless chrome. I haven't had a chance to play around with headless chrome myself yet, but if I have some spare cycles in the near future I'll give it a shot.

**Pull request merged**
