### PR TITLE
Remove jQuery dependency, replace Bower package with NPM, fix tests

### PR DESCRIPTION
**Pull request by leizhao4**
- `jquery.inputmask` is now called just `Inputmask` and jQuery is no longer a requirement. I replaced the original jQuery plugin with the new vanilla library.
- Since Ember is moving away from Bower, I removed the Bower dependency of `jquery.inputmask` and added the NPM dependency. Blueprint has been removed too.
- Moved all tests from `/unit` to `/integration` because they are supposed to be integration tests.
- Replaced jQuery-based test helpers with native ones using `ember-native-dom-helpers`.
- Fixed tests that were not working.
- Bumped Node to 6.
- Bumped Ember and Ember CLI to 2.12.
- Bumped some dependencies.
- Updated Travis CI and ember-try configs.
- Added `yarn.lock` file.
- Removed deprecation notice from README. This addon is still very useful. Don't deprecate it! :)

### CODE REVIEW

**Comment by leizhao4** [comment]
Hi @pzuraq! Sorry this is a really big pull request, but I'm using this addon in my project so I have to fork it and update many of these things. If you could review and merge it and release a new version then it would be awesome. Please let me know any concerns.

**Comment by pzuraq** [comment]
Hey @leizhao4, like it says in the Readme I'm not actually maintaining this project anymore. However, totally happy to hand it off. Would you like to be made a contributor and given NPM publish rights?

**Comment by leizhao4** [comment]
@pzuraq Yes I would love to help.

**Comment by pzuraq** [comment]
Cool, just added you as a contributor. What's your NPM user name?

**Comment by leizhao4** [comment]
Thanks a lot! My NPM username is `leizhao4` too.

**Comment by pzuraq** [comment]
Cool, added! Thanks for taking over, definitely appreciate it!

**Pull request merged**
