### PR TITLE
remove extra digit for amex cards

### PR DESCRIPTION
**Pull request by AO16**

### CODE REVIEW

**Comment by pzuraq** [comment]
@AO16 Thanks for taking this on! It looks like you need to update the AMEX test as well, super small change. I'll merge it as soon as you get that in!

**Comment by pzuraq** [comment]
@AO16 Would love to merge this PR but gotta get those tests passing, think you'll have the time to fix those soon?

**Comment by AO16** [comment]
@pzuraq Yep, I'll do it right now. Sorry, this got completely lost on my end.

**Comment by AO16** [comment]
@pzuraq Encountered another test that was failing https://github.com/pzuraq/ember-inputmask/issues/19

**Comment by AO16** [comment]
Closing for now until the other issue is resolved

**Comment by pzuraq** [comment]
@AO16 Yeah I've been taking a look, it's because the Amex credit card mask binding doesn't change until the blur event is triggered on the input, which means that you can't enter the extra digit. We can hack around this for now by putting American Express at the end, but this is why I ultimately wanted to rebuild inputmasks in native Ember. I can fix the test and resubmit the PR.

**Pull request closed without merging**
