### PR TITLE
Added ssn-input component, updated addon to use latest ember-cli

### PR DESCRIPTION
**Pull request by tushar-chauhan**
@pzuraq I had a requirement in my project where this addon helped me a lot. I have made some upgrades to this addon. I hope you find them useful.

This pull request includes:
* New `{{ssn-input}}` component with unit test
* Upgraded ember-cli and most of other dependencies to latest ember version
* Cleanup failing email-input test
* Cleanup of the dummy app

### CODE REVIEW

**Comment by pzuraq** [comment]
@tushar-chauhan This looks good! My one question is about the commented out test, is it an incorrect test or could you just not get it working again? If it's incorrect we should remove it, but if it is correct and not working we'll need to diagnose and fix.

**Comment by tushar-chauhan** [comment]
@pzuraq if you uncomment and try that test out, you will see that the unmaskedValue is same as the input value. 
I tried to fix it, but I could not find any code in the email-input component, rather I found out that it is totally inherited from input-mask component.

As that test was failing after upgrade, I commented it.

Right now I am on a holiday and not carrying my machine, so I won't be able to look into it before 9th of this month. Let me know if you try that test and get it running before that.

**Comment by tushar-chauhan** [comment]
One solution could be to change that assertion to:
`assert.equal(component.get('unmaskedValue'), 'test@test.test');`

**Comment by tushar-chauhan** [comment]
I guess you can do replace: `assert.equal(component.get('unmaskedValue'), 'testtesttest');` with 
`assert.equal(component.get('unmaskedValue'), 'test@test.test');`

I just checked email tests on jquery.inputmask: https://github.com/RobinHerbots/jquery.inputmask/blob/3.x/qunit/tests_dynamic.js

When entire email id is in the input field then they are also asserting it with the same full email id. I hope this helps. My fingers are killing me while typing on mobile now :smile:

**Comment by pzuraq** [comment]
@tushar-chauhan That makes sense, looks like the test was flawed to begin with. Go ahead and replace the value, it's much better than commenting out the test. I'll merge as soon as it's updated, thank you for contributing!

**Comment by tushar-chauhan** [comment]
@pzuraq Updated the pull request with cleaned up tests. I have added both assertions in a single test. Let me know if something needs to be changed.

**Comment by tushar-chauhan** [comment]
@pzuraq You may want too add the usage instruction for `ssn-input` field in the Readme file too.

**Comment by pzuraq** [comment]
@tushar-chauhan Right on, I'll merge this as is. I'm not actively maintaining this plugin at the moment, but will continue to review and merge PRs, so feel free to add any docs or make any changes!

**Pull request merged**
