### PR TITLE
Added phone-number-input with code

### PR DESCRIPTION
**Pull request by listepo**

### CODE REVIEW

**Comment by pzuraq** [comment]
@listepo Looks good! Can you add a test for the code part?

**Comment by listepo** [comment]
@pzuraq, yes

**Comment by listepo** [comment]
@pzuraq jquery.inputmask 3.2.2 ENOENT, no such file or directory '/Users/ivan/github/research/ember-inputmask/tmp/concat_with_maps-input_base_path-I1QCaVKT.tmp/0/bower_components/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js'

**Comment by pzuraq** [comment]
@listepo that error generally means that a file is missing, are you still encountering it?

**Comment by listepo** [comment]
@pzuraq yes, see https://github.com/RobinHerbots/jquery.inputmask/tree/3.x/dist/min https://github.com/RobinHerbots/jquery.inputmask/tree/3.2.0/dist/min

**Comment by blimmer** [comment]
I bet you've got an old version of input-mask in your bower directly. I'd try a [nombom](https://github.com/pzuraq/nombom)

**Comment by pzuraq** [comment]
@listepo I'm going to close this PR out for now due to merge conflicts. If you want to resubmit with passing tests, feel free!

**Pull request closed without merging**
