### PR TITLE
Feature/amex credit card

### PR DESCRIPTION
**Pull request by pzuraq**
@AO16

### CODE REVIEW

**Comment by AO16** [comment]
:+1:

**Comment by AO16** [comment]
@pzuraq Do you have any plans to integrate this more within Ember?

**Comment by pzuraq** [comment]
I'm actually going to update the README to make it more clear, haven't communicated to well which is my fault, but I consider this component deprecated for a number of reasons. The biggest problem is performance, but it's also clunky with events and such like the problem this test showed. 

This comes down to the fact that we are trying to wrap a Jquery plugin rather than doing input masks in native Ember. I've been meaning to make a native Ember input mask component for a while, but haven't had the time. It's clear that a lot of people are using this and need this functionality though, I'll see if I can hack something out over Emberconf :wink:

**Comment by AO16** [comment]
@pzuraq :+1: If you end up doing that, I'd be happy to help contribute. Thanks for the work!

**Comment by pzuraq** [comment]
@AO16 Are you on the Ember community slack? Thought about it a bit and the problem is difficult for a number of reasons, I'm thinking it might make more sense to focus on certain types of masks over others and would like to talk about it. Reproducing the functionality of `jquery.inputmask` may not be feasible.

**Comment by AO16** [comment]
@pzuraq Currently not on ember community slack. Is there an easy way to get an invite?

**Pull request merged**
